**Importing the necessary modules**

In [64]:
import pandas as pd 
import numpy as np


 **NumPy  version used** 












In [65]:
np.__version__

'1.19.5'

**Pandas Version Used**

In [66]:
pd.__version__

'1.1.5'

**Loading the data**

>Download the dataset here [CAR DATASET]( https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
)



In [67]:
df=pd.read_csv("/content/drive/MyDrive/DATA_ML/data.csv")

**Initial Exploration of the DATA**

In [68]:
df.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

**Subsetting the rows based on BMW cars**

In [70]:
 bmw_cars = df[df["Make"] == "BMW"]
 print(bmw_cars)

      Make       Model  Year  ... city mpg  Popularity    MSRP
0      BMW  1 Series M  2011  ...       19        3916   46135
1      BMW    1 Series  2011  ...       19        3916   40650
2      BMW    1 Series  2011  ...       20        3916   36350
3      BMW    1 Series  2011  ...       18        3916   29450
4      BMW    1 Series  2011  ...       18        3916   34500
...    ...         ...   ...  ...      ...         ...     ...
11901  BMW          Z4  2016  ...       22        3916   49700
11902  BMW          Z4  2016  ...       17        3916   66350
11903  BMW          Z8  2001  ...       12        3916  128000
11904  BMW          Z8  2002  ...       12        3916  130000
11905  BMW          Z8  2003  ...       12        3916  131500

[334 rows x 16 columns]


**Creating the New Data Frame with the above got array**

In [71]:
mini_df = pd.DataFrame(bmw_cars)

**Grouping the dataframe by Make column to get the Mean of the prices**

In [72]:
mini_df.groupby('Make')['MSRP'].mean()

Make
BMW    61546.763473
Name: MSRP, dtype: float64

**Again subsetting the dataframe using relational operator to return True or False for each row, then passing that inside square bracket**

> subset of cars after year 2015 ( i.e. 2015 and after)



In [73]:
y_2015 = df[df["Year"]>= 2015]
print(y_2015)

       Make       Model  Year  ... city mpg  Popularity   MSRP
32     FIAT  124 Spider  2017  ...       26         819  27495
33     FIAT  124 Spider  2017  ...       26         819  24995
34     FIAT  124 Spider  2017  ...       26         819  28195
41      BMW    2 Series  2016  ...       23        3916  32850
42      BMW    2 Series  2016  ...       23        3916  38650
...     ...         ...   ...  ...      ...         ...    ...
11898   BMW          Z4  2015  ...       17        3916  56950
11899   BMW          Z4  2015  ...       17        3916  65800
11900   BMW          Z4  2016  ...       17        3916  57500
11901   BMW          Z4  2016  ...       22        3916  49700
11902   BMW          Z4  2016  ...       17        3916  66350

[5995 rows x 16 columns]


**Finding in any missing values, if there in Engine HP column of the dataset**

> Using isnull() function to get the null values, followed by sum() function to get the total of null value



In [74]:
missing_HP = y_2015["Engine HP"].isnull().sum()
print(missing_HP)

51


**Finding average of Engine HP column**


1.   Average with null values as it is and rounded off
2.   Average when all null values are filled with Previously got mean and rounded off





In [75]:
avg_HP_before = df["Engine HP"].mean()
print(round(avg_HP_before))

249


In [76]:
df["Engine HP"].fillna(249, inplace = True)
avg_HP_after = df["Engine HP"].mean()
print(round(avg_HP_before))

249


**Subsetting rows on Make column to get all Rolls-Royce cars**

> Filtering the above got using LOC function which is primarily Label Based to get desired data frame with "Engine HP", "Engine Cylinders", "highway MPG" columns



In [77]:
 rr_cars = df[df["Make"]== "Rolls-Royce"]

filter_rr = rr_cars.loc[:,["Engine HP", "Engine Cylinders", "highway MPG"]]
print(filter_rr)

       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0      

**Dropping Duplicate values if any**

> Using .drop_duplicate() function to remove duplicates 



In [78]:
 X = filter_rr.drop_duplicates()
print(X)


       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21


**Computing the transpose of the above got array**

In [79]:
X_transpose = X.T
print(X_transpose)




                  2921   3505   5275   5279   7443   7553   11448
Engine HP         325.0  563.0  563.0  563.0  322.0  453.0  624.0
Engine Cylinders    8.0   12.0   12.0   12.0   12.0   12.0   12.0
highway MPG        15.0   19.0   21.0   20.0   15.0   19.0   21.0


**Matrix multiplication of two arrays**

> Using NumPy .dot function



In [80]:
XTX = X_transpose.dot(X)


**Finding the inverse of above array and sum of all its elements**

> Using numpy.linalg.inv() to compute the (multiplicative) inverse of a matrix

> Using sum() function to get the sum







In [81]:
XTX_inverted = np.linalg.inv(XTX)
print(XTX_inverted)
XTX_inverted.sum()


[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


0.032212320677486125

**Creating an array and multiplyingg to get the desired results**

In [82]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
mltiply = XTX_inverted.dot(X_transpose)
w = mltiply.dot(y)
print(w)

[ 0.19989598 31.02612262 31.65378877]
